language: go
sudo: false
go:
  - 1.9
os:
  - windows
  - linux 
go_import_path: github.com/aws/amazon-ecs-agent
script:
  - |
    (
      if [ "$TRAVIS_OS_NAME" = 'windows' ]; then
        go test -race -tags unit -timeout 40s ./agent/...
      else
        make get-deps
        make test
        make static-check
        make xplatform-build
      fi
    )
